app/auth.py
import os
from . import mail
from flask import (flash, render_template, redirect,
                   request, session, url_for, Blueprint)
from werkzeug.security import generate_password_hash, check_password_hash
# flask mail
from flask_mail import Message
# encoding / decoding tokens
import jwt
from datetime import datetime, timedelta
from bson.objectid import ObjectId
from time import time
from app.validators import validators
# Classes
from app.models.user import User
from app.models.notifications import Notification
from app.models.event import Event
from app.models.group import Group


# Blueprint
auth = Blueprint("auth", __name__)


# Sign up functionality
@auth.route("/signup", methods=["GET", "POST"])
def signup():
    """
    Check if user email exists,
    If so, add flash message informing user
    Check if data are valid
    Create a signup dictionary from user input
    Insert in MongoBD if data is valid and,
    Add the new user email into 'session' cookie
    Redirect to complete profile page
    """
    if request.method == "POST":
        # check if email already exists
        existing_user = User.check_existing_user(request.form.get(
                                                 "email").lower())

        if existing_user:
            flash("Username already exists, please sign in")
            return redirect(url_for("auth.signup"))

        # form validation
        valid = all(validators.signup_validation(request.form.get("password"),
                    request.form.get("fname"), request.form.get("lname")))

        if valid:
            new_user = User(first_name=request.form.get("fname").lower(),
                            last_name=request.form.get("lname").lower(),
                            email=request.form.get("email").lower(),
                            password=request.form.get("password"))

            new_user.insert_into_database()

            flash("Sign up successful!")
            session['email'] = request.form['email'].lower()

            return redirect(url_for("auth.complete_profile",
                                    email=session["email"]))

        else:
            return redirect(url_for("auth.signup"))

    return render_template("signup.html")


# Complete profile functionality
# https://testdriven.io/blog/flask-sessions/
@auth.route("/complete_profile/<email>", methods=["GET", "POST"])
def complete_profile(email):
    """
    Get email, first name and user ID from MongoDB
    Build dictionary from user input
    Add group if group name is not empty
    Update user in MongoDB
    Flash message to inform user of successful completion
    Redirect to complete profile completed page
    If url image not valid, return complete profile,
    Flash message to inform user profile couldn't be completed
    """
    user = User.check_existing_user(email)
    if not user:
        return redirect(url_for("auth.login"))

    # Get the first name for session user from MongoDB
    fname = User.check_existing_user(email)["first_name"].capitalize()

    if request.method == "POST":

        profile = {"user_imgUrl": request.form.get("user-img"),
                   "city": request.form.get("city"),
                   "country": request.form.get("country"),
                   "preferences": {"event_reminder": validators.check_box(
                                    request.form.get("event_reminder")),
                                   "query_answered": validators.check_box(
                                     request.form.get("query_answered")),
                                   "event_update": validators.check_box(
                                     request.form.get("event_update")),
                                   "new_participant": validators.check_box(
                                     request.form.get("new_participant")),
                                   "event_question": validators.check_box(
                                     request.form.get("event_question")),
                                   "new_follower": validators.check_box(
                                     request.form.get("new_follower"))},
                   "profile_completed": True}

        check = validators.check_img_url(request.form.get("user-img"))
        if check:
            User.edit_user(user["_id"], profile)

            # Add group
            if request.form.get("group_name"):
                new_group = Group(group_name=request.form.get("group_name"),
                                  group_city=request.form.get("city"),
                                  group_country=request.form.get("country"),
                                  group_description="",
                                  img_url="",
                                  group_admin=[user["_id"]])
                new = new_group.insert_into_database()
                User.append_list(user["_id"], "group_owned", new.inserted_id)

            flash("Congratulations, profile successfully completed!")
            return redirect(url_for("auth.profile_completed",
                                    email=session["email"]))
        else:
            flash("We couldn't complete your profile, please "
                  "provide a valid image url.")
            return redirect(url_for('auth.complete_profile',
                            email=session["email"]))
    return render_template(
            "complete-profile.html", email=email, name=fname)


@auth.route("/profile_completed/<email>")
def profile_completed(email):
    """
    Get email and first name from MongoDB
    Display page if user in session
    """
    if session["email"]:
        fname = User.check_existing_user(email)["first_name"].capitalize()
        return render_template(
            "profile-completed.html", email=email, name=fname)


# Log in
@auth.route("/login", methods=["GET", "POST"])
def login():
    """
    Get existing user from MongoDB
    Check if existing user
    If existing user, check password
    If existing user, check events happening with next 2 days and,
    Add notification if not already notified and preference setting is true
    If password match redirect to profile completed
    If no password match, redirect to login page and,
    Inform user password is incorrect
    If no existing user, flash message to inform user
    """

    if request.method == "POST":
        # Check if user exists in DB
        user = User.check_existing_user(request.form.get("email").lower())

        if user:
            # check if passowrd matches
            pwd = request.form.get("password")
            existing_user_pwd = user["password"]

            if check_password_hash(existing_user_pwd, pwd):

                # put user in session
                session["email"] = request.form.get("email").lower()

                # notifications
                initial_date = datetime.now()

                end_check = initial_date + timedelta(days=2)

                iso_start = initial_date.strftime('%Y-%m-%dT%H:%M:%S')
                iso_end = end_check.strftime('%Y-%m-%dT%H:%M:%S')

                isos = datetime.strptime(iso_start, '%Y-%m-%dT%H:%M:%S')
                isoe = datetime.strptime(iso_end, '%Y-%m-%dT%H:%M:%S')

                events = list(Event.find_events_by_dates(isos, isoe))

                if len(events) > 0:
                    for event in events:
                        send_to = []
                        # Check if attendee already notified
                        already_notified = list(Notification.already_notified(
                                            event["_id"], user["_id"]))
                        if len(already_notified) == 0:
                            for attendee in event["attendees"]:
                                att = User.find_user_by_id(attendee)
                                """
                                Create notification if match attendee &
                                event reminder preference is true
                                """
                                if att["_id"] == user["_id"] and user[
                                   "preferences"]["event_reminder"] == "true":
                                    send_to.append(ObjectId(user["_id"]))
                                    notification = (
                                        Notification.set_col_reminder(
                                         send_to, event["_id"]))
                                    Notification.insert_notification(
                                     notification)

                # redirects to profile completed or complete your profile
                if user["profile_completed"] is True:
                    return redirect(url_for("auth.profile_completed",
                                    email=user["email"]))
                if user["profile_completed"] is False:
                    return redirect(url_for("auth.complete_profile",
                                    email=user["email"]))
            else:
                flash("Incorrect password")
                return redirect(url_for("auth.login"))

        else:
            # username doesn't exist
            flash("Incorrect email and/or password")
            return redirect(url_for("auth.login"))

    return render_template("login.html")


# Log out
@auth.route("/logout")
def logout():
    """
    Remove user from session cookies
    Flash message to inform user
    Redirect to login page
    """
    session.pop("email", None)
    flash("You have been logged out")
    return redirect(url_for("auth.login"))


"""
Reset password
https://medium.com/@stevenrmonaghan/password-reset-with-flask-mail-protocol-ddcdfc190968
"""


# Get token for reset link
def get_reset_token(email, expires=500):
    """
    Return a token to encode user email
    """
    return jwt.encode({'user': email,
                       'exp':    time() + expires},
                      key=os.environ.get("SECRET_KEY"))

app/main.py
import os
from . import mail
from flask import (flash, render_template, redirect,
                   session, request, url_for, Blueprint)
# flask mail
from flask_mail import Message
from app.models.event import Event
from app.models.group import Group
from app.models.user import User


# Blueprint
main = Blueprint("main", __name__)


# Search
@main.route("/search", methods=["GET", "POST"])
def search():
    """
    Render template for all groups and events according to
    search query
    Pass variables so that relevant group and event action are
    displayed
    """
    if session:
        user = User.check_existing_user(session["email"])
    else:
        user = None
    query = request.form.get("search")
    events = list(Event.search_events(query))
    groups = list(Group.search_groups(query))
    users = User.find_all_users()

    if user:
        events_attending = list(user["events_attending"])
        events_interest = list(user["events_interest"])
        events_organised = list(user["events_organised"])
        followed = list(user["group_following"])
        owned = list(user["group_owned"])
    else:
        events_attending = []
        events_interest = []
        events_organised = []
        owned = []
        followed = []

    return render_template("browse-events-groups.html",
                           events=events, groups=groups,
                           query=query, user=user,
                           users=users, events_attending=events_attending,
                           events_interest=events_interest,
                           events_organised=events_organised,
                           owned=owned, followed=followed, search=True)


# Homepage
@main.route("/")
@main.route("/home")
def home():
    """
    Render template for homepage
    Fetch the latest 6 coming events
    If user in session, pass variables so that the relevant actions for
    events are displayed
    """
    # Variables
    events = Event.upcoming_events()
    total = len(Event.find_all_active_events())
    users = User.find_all_users()
    if session.get("email"):
        user = User.check_existing_user(session["email"].lower())
    else:
        user = None
    if user:
        events_attending = list(user["events_attending"])
        events_interest = list(user["events_interest"])
        events_organised = list(user["events_organised"])
    else:
        events_attending = []
        events_interest = []
        events_organised = []
    return render_template("home.html", events=events, users=users,
                           total=total, user=user,
                           events_attending=events_attending,
                           events_interest=events_interest,
                           events_organised=events_organised)


# All events and groups
@main.route("/browse_events_groups/")
def browse_events_groups():
    """
    Render template for all groups and events
    Find all active and current events
    If user in session, pass the variables so that
    relevant user actions for groups and events are displayed
    """
    events = Event.find_all_active_events()
    groups = Group.find_all_groups()
    users = User.find_all_users()

    if session.get("email"):
        user = User.check_existing_user(session["email"].lower())
    else:
        user = None

    if user:
        events_attending = list(user["events_attending"])
        events_interest = list(user["events_interest"])
        events_organised = list(user["events_organised"])
        followed = list(user["group_following"])
        owned = list(user["group_owned"])
    else:
        events_attending = []
        events_interest = []
        events_organised = []
        owned = []
        followed = []
    return render_template("browse-events-groups.html", events=events,
                           groups=groups, users=users, user=user,
                           events_attending=events_attending,
                           events_interest=events_interest,
                           events_organised=events_organised,
                           owned=owned, followed=followed)


""""
https://sendgrid.com/blog/sending-emails-from-python-flask-applications-with-twilio-sendgrid/
"""


@main.route("/contact_us", methods=['GET', 'POST'])
def contact_us():
    """
    Get input from user in contact form
    Send a acknowledgment email to suer
    Send email with email, fullname and message to the website owner
    Lets user know the email has been sent
    """
    if request.method == 'POST':
        sender_fullname = request.form['fullname']
        sender_email = request.form['email']
        sender_message = request.form['message']
        admin_email = os.environ.get('MAIL_DEFAULT_SENDER')
        recipients = [sender_email, admin_email]
        # flask documentation https://pythonhosted.org/Flask-Mail/
        with mail.connect() as conn:
            for recipient in recipients:
                if recipient == admin_email:
                    message = (f"<h3>Hello</h3>"
                               "<p>Please find below message from:</p>"
                               f"<p><b>Name:</b> {sender_fullname}</p> "
                               f"<p><b>Email:</b> {sender_email}</p> "
                               f"<p><b>Message:</b> {sender_message} </p>")
                    subject = f"New query from: {sender_fullname}"

                elif recipient == sender_email:
                    message = (f"<h3>Hello {sender_fullname},</h3>"
                               "<p>We have received your message and aim"
                               " to respond within the next 2 working "
                               "days.</p>"
                               "<p>Best regards</p>"
                               "<p>Codzilla Team</p>"
                               )
                    subject = 'Thank your for your query'

                msg = Message(recipients=[recipient],
                              html=message,
                              subject=subject)
                conn.send(msg)

        flash("Your message was sent successfully!")
        return redirect(url_for('main.contact_us'))
    return render_template("contact_us.html")


# Accessibility page
@main.route("/accessibility")
def accessibility():
    """
    Return template for accessibility page
    """
    return render_template("accessibility.html")


# Frequently asked question page
@main.route("/faq")
def faq():
    """
    Return template for Frequently Asked Question
    """
    return render_template("faq.html")


# Privacy page
@main.route("/privacy")
def privacy():
    """
    Return template for privacy page
    """
    return render_template('privacy.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon.png')}}">
  <meta name="Description" content="Codzilla brings coders together for social, networking and collaborative events">
  <meta name="keywords" content="event, meetup, coding meetup, coding event, networking, tech meetup">
  <meta name="author" content="Claire Lemonnier">

  {% block styles %}
  {% endblock %}
  <!-- Font awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    type="text/css">
  <!-- Materialize -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}" type="text/css">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <!-- Navbar -->
  <header>
    <nav>
      <div class="nav-wrapper transparent">
        <a href="{{ url_for('main.home') }}" class="brand-logo left">codzilla</a>

        {% if session.email %}

        <!-- Navigation user not in session -->
        <ul class="right">
          <li>
            <a class="nav-item" href="{{ url_for('main.home') }}" aria-label="Go to homepage">
              <i class="fas fa-home" aria-hidden="true"></i>
            </a>
          </li>
          <li>
            <a class="nav-item" href="{{ url_for('users.notifications') }}" aria-label="Go to notification page">
              <i class="fas fa-bell" aria-hidden="true"></i>
              {% if session.email %}
              {% if new|int > 0 %}
              <span class="btn-floating new-notification">{{ new }}</span>
              {% endif %}
              {% endif %}
            </a>
          </li>
          <li>
            <a class="nav-item" href="{{ url_for('events.add_event') }}" aria-label="Go to add event page">
              <i class="far fa-calendar-plus" aria-hidden="true"></i>
            </a>
          </li>
          <li><a class="nav-item" href="{{ url_for('main.browse_events_groups') }}"
              aria-label="Go browse all groups and events">
              <i class="fas fa-search" aria-hidden="true"></i>
            </a>
          </li>
          <li>
            <button class="nav-item dropdown-trigger" data-target="profile" data-beloworigin="true"
              aria-label="View dropdown menu for user">
              <i class="fas fa-user" aria-hidden="true"></i>
            </button>
          </li>
        </ul>

        <ul id="profile" class='dropdown-content z-depth-5'>
          <li><a href="{{ url_for('users.profile') }}">My profile</a></li>
          <li><a href="{{ url_for('users.my_events') }}">My events</a></li>
          <li><a href="{{ url_for('users.my_groups') }}">My groups</a></li>
          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        </ul>

        {% else %}
        <!-- Navigation user not in session -->

        <button data-target="mobile" data-beloworigin="true" aria-label="open dropdown menu"
          class="dropdown-trigger hide-on-large-only right">
          <i class="nav-btn fas fa-bars" aria-hidden="true"></i></button>

        <ul class="right hide-on-med-and-down">
          <li><a class="nav-item nav-text" href="{{ url_for('main.home') }}">Home</a></li>
          <li><a class="nav-item nav-text" href="{{ url_for('auth.login') }}">Log in</a></li>
          <li><a class="nav-item nav-text" href="{{ url_for('auth.signup') }}">Sign up</a></li>
          <li><a class="nav-item nav-text" href="{{ url_for('main.browse_events_groups')}}">All groups & events</a></li>
        </ul>

        <!-- Mobile nav -->
        <ul id="mobile" class='dropdown-content hide-on-large-only z-depth-5'>
          <li><a href="{{ url_for('main.home') }}">Home</a></li>
          <li><a href="{{ url_for('auth.login') }}">Log in</a></li>
          <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
          <li><a href="{{ url_for('main.browse_events_groups')}}">All groups & events</a></li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </header>

  <!-- Content -->
  <main class="container">
    {% block content%}
    {% endblock %}
  </main>

  <!-- Footer -->
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 class="footer-text">Codzilla</h2>
          <p class="footer-text">Meet, connect and develop with fellow coders!</p>
          <a class="btn contact-btn" href="{{ url_for('main.contact_us') }}">Contact us</a>
        </div>
        <div class="col l4 offset-l2 s12">
          <h2 class="black-text">Useful links</h2>
          <ul>
            <li><a class="footer-text" href="{{ url_for('auth.login') }}">Log in</a></li>
            <li><a class="footer-text" href="{{ url_for('auth.signup') }}">Sign up</a></li>
            <li><a class="footer-text" href="{{ url_for('main.faq') }}">F.A.Q</a></li>
            <li><a class="footer-text" href="{{ url_for( 'main.privacy' )}}">Privacy</a></li>
            <li><a class="footer-text" href="{{ url_for('main.accessibility') }}">Accessibility</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container footer-text">
        © 2021 Copyright Claire Lemonnier
      </div>
    </div>
  </footer>

  <!--scripts-->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  {% block scripts %}
  {% endblock %}
  <script src="{{ url_for('static', filename='js/script.js')}}"></script>

</body>

</html>

app/templates/my-groups.html
{% extends "base.html" %}
{% block title %}My groups{% endblock %}

{% block content %}
<div class="row head-container">
    <div class="col s12 l8 offset-l2">
        <h1 class="center-align">My groups</h1>
        <hr class="breakline">
    </div>
</div>

<!-- Tabs -->
<div class="row">
    <div class="col s12">
        <ul class="tabs">
            <li class="tab col s6 btn-tab"><a class="active" href="#view-group-owning">owning</a></li>
            <li class="tab col s6 btn-tab"><a href="#view-group-following">following</a></li>
        </ul>
    </div>
</div>

<!-- Group admin -->
<div class="row" id="view-group-owning">
    <div class="col s12 m6">
        <h2>My groups as an owner</h2>
    </div>
    <div class="col s12 m6 col-add-group">
        <a href="{{ url_for('groups.add_group')}}" class="btn btn-send">Add a group</a>
    </div>
    <div class="col s12 center-align flashes">
        {% with messages = get_flashed_messages() %}
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
        {% endwith %}
    </div>
    {% if groups_owned|length > 0 %}
    {% for group in groups_owned %}
    <div class="col s12 margin-top">
        <div class="div card horizontal hoverable">
            <div class="card-image">
                {% if group.img_url == "" or group.img_url is none %}
                <img class="horizontal-card-img" src="{{ url_for('static', filename='images/group_default.png')}}"
                    width="368" height="173" alt="default event cover">
                {% else %}
                <img class="horizontal-card-img" src="{{ group.img_url }}" width="368" height="173" data-default="group"
                    alt="group cover for {{ group.group_name }}">
                {% endif %}
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <a class="page-link" href="{{ url_for('groups.group', group_id=group._id)}}">
                        <h3 class="event-title">{{ group.group_name.capitalize() }}</h3>
                    </a>
                    <p class="location">{{ group.group_city.capitalize() }}, {{ group.group_country.capitalize() }}</p>
                    <p class="gp-description truncate">{{ group.group_description }}</p>
                    <div class="card-action">
                        <div class="row action-container">
                            <div class="col s12 m6 valign-wrapper">
                                <p><i class="fas fa-user-circle attendees"></i>{{ group.group_members|length }}
                                    member(s)</p>
                            </div>
                            <div class="col s12 m6 small-pd-top align-right-md">
                                <a class="btn btn-send mg-right"
                                    href="{{ url_for('groups.edit_group', group_id=group._id)}}">Edit</a>
                                <a class="btn btn-send modal-trigger"
                                    href="#delete-confirmation-{{ group._id }}">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- modal delete confirmation -->
        <div id="delete-confirmation-{{ group._id }}" class="modal">
            <div class="row modal-content">
                <div class="col s12 center-align margin-bottom">
                    <i class="far fa-times-circle close-form modal-close"></i>
                    <h2>Delete group confirmation</h2>
                    <hr class="breakline">
                    <p>Are you sure you want to delete the following group?</p>
                    <p><b>{{ group.group_name }}</b></p>
                </div>
                <!-- form delete event -->
                <form class="col s12 center-align p-separator" method="POST"
                    action="{{ url_for('groups.delete_group', group_id=group._id) }}">
                    <button class="btn btn-send margin-top mg-right" type="submit">confirm</button>
                    <a href="#" class="btn btn-send margin-top modal-close">cancel</a>
                </form>
            </div>
        </div>
        <!--end section-->
    </div>
    {% endfor %}
    {% else %}
    <div class="col s6 offset-s3 m4 offset-m4 margin-top">
        <img class="responsive-img" src="{{ url_for('static', filename='images/support-team.svg')}}" width="520"
            height="450" alt="illustration of a group of people around a computer">
    </div>
    <div class="col s12 center-align">
        <h3>You don't own any groups</h3>
    </div>
    {% endif %}
</div>

<!-- Group members-->
<div class="row" id="view-group-following">
    <div class="col s12">
        <h2>My groups as a member</h2>
    </div>
    {% if groups_following|length > 0 %}
    {% for group in groups_following %}
    <div class="col s12" id="card-{{ group._id }}">
        <div class="div card horizontal hoverable">
            <div class="card-image">
                {% if group.img_url == "" or group.img_url is none %}
                <img class="horizontal-card-img" src="{{ url_for('static', filename='images/group_default.png')}}"
                    width="368" height="173" alt="default group cover">
                {% else %}
                <img class="horizontal-card-img" src="{{ group.img_url }}" width="368" height="173" data-default="group"
                    alt="group cover for {{ group.group_name }}">
                {% endif %}
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <a class="page-link" href="{{ url_for('groups.group', group_id=group._id)}}">
                        <h3 class="event-title">{{ group.group_name.capitalize() }}</h3>
                    </a>
                    <p class="location">{{ group.group_city.capitalize() }}, {{ group.group_country.capitalize() }}</p>
                    <p class="gp-description truncate">{{ group.group_description.capitalize() }}</p>
                    <!-- Actions buttons -->
                    <div class="card-action">
                        <div class="row action-container valign-wrapper">
                            <div class="col s6 valign-wrapper">
                                <p>
                                    <i class="fas fa-user-circle attendees"></i>
                                    {{ group.group_members|length }} member(s)
                                </p>
                            </div>
                            <div class="col s6 right-align">
                                <!-- group members action -->
                                <button class="btn btn-following" data-user="{{ user._id }}"
                                    data-group="{{ group._id}}">Following</button>
                                <button class="btn btn-unfollow hide" data-user="{{ user._id }}"
                                    data-group="{{ group._id}}">Unfollow</button>
                                <!-- end group action -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col s6 offset-s3 m4 offset-m4 margin-top">
        <img class="responsive-img" src="{{ url_for('static', filename='images/support-team.svg')}}" width="520"
            height="450" alt="Illustration of a group of people around a computer">
    </div>
    <div class="col s12 center-align">
        <h3>You don't follow any groups </h3>
        <a href="{{ url_for('main.browse_events_groups')}}" class="btn btn-send">Browse groups & events</a>
    </div>
    {% endif %}
</div>

{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/event_group_actions.js')}}"></script>
{% endblock %}

app/templates/reset-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset password email</title>
</head>
<body>
    <p><strong>Hello</strong></p>
    <p>Please find the link to reset your password:</p>
    <a href="{{ url_for('auth.reset_password', token=token, _external=True) }}">link to reset password</a>
    <p>Kind regards</p>
    <p>Codzilla team</p>
</body>
</html>